### ISSUE TITLE
Retrieving data subsets

### ISSUE THREAD

**Issue by jbvi** [SantanderMetGroup/loadeR.ECOMS#4]
Good day,

After the server downtime yesterday, there appears to be some issues with retrieving data subsets. 

An loadECOMS example request:
 prd <- loadECOMS(dataset = "System4_seasonal_15", 
                     var = "tas", time = "DD",
                     season = c(12,1,2,3,4,5), 
                     members = 1:2, 
                     leadMonth = 1,
                     lonLim = c(-15,35),
                     latLim = c(32, 75),
                     years = c(2001:2010))

Now returns URL error:
[2017-04-07 10:07:35] Defining harmonization parameters for variable "tas"
[2017-04-07 10:07:36] Opening dataset...
Error: The requested dataset URL was not found (HTTP error 404)

**Comment by jbedia** [comment]
Hi. The UDG server won't be operative until Monday for maintenance operations. Sorry for the inconvenience.
