### ISSUE TITLE
loadeR.ECOMS installation error on R3.4

### ISSUE THREAD

**Issue by suraj500** [SantanderMetGroup/loadeR.ECOMS#5]
Hi, 
      I am gating following error while installing loadeR.ECOMS on R 3.4.4 with Java 10
"
installing *source* package ‘loadeR.ECOMS’ ...
Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII
Error in iconv(x[ind], "latin1", "ASCII", sub = "byte") : 
  object 'ind' not found
ERROR: installing package DESCRIPTION failed for package ‘loadeR.ECOMS’
* removing ‘/Library/Frameworks/R.framew"
"

Can you suggest which version of loadeR.ECOMS I shall install on R 3.4

Thanks
Suraj

**Comment by jbedia** [comment]
Hi,
we have recently come across this error in other places and it has in principle nothing to do with `loadeR.ECOMS` (see e.g. [this post](https://github.com/r-lib/devtools/issues/1734)). It seems that is related with an already known [bug in R3.4.4 source code](https://github.com/wch/r-source/blame/tags/R-3-4-4/src/library/tools/R/utils.R#L1769) (L1769). One possible workaround is to go back to R3.4.3.

**Comment by suraj500** [comment]
Thanks,
              I upgraded to the R 3.5 and problem resolved with loadeR.ECOMS installation

Thanks again
Suraj

**Comment by jbedia** [comment]
Excellent. I'll close this issue now. Thanks
